'use client';

import { useWallet } from '@solana/wallet-adapter-react';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Navbar } from '@/components/Navbar';
import { motion } from 'framer-motion';
import { Shield, Lock, Award, Zap, Wallet, BarChart2, Unlock, ChevronDown } from 'lucide-react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import styles from './page.module.css';

const WalletMultiButtonDynamic = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletMultiButton,
  { ssr: false }
);

const FAQ_ITEMS = [
  {
    q: 'What is a FairScore?',
    a: "A FairScore is a 0–100 reputation score generated by FairScale's infrastructure. It analyzes your Solana wallet's on-chain activity — transaction history, DeFi participation, staking, and NFT holdings — to produce a verifiable, tamper-proof score."
  },
  {
    q: 'Which wallets are supported?',
    a: 'FairGate supports all Wallet Standard compatible wallets including Phantom, Solflare, Coinbase Wallet, and Backpack. If your wallet supports Solana and follows the Wallet Standard spec, it will work out of the box.'
  },
  {
    q: 'Is my data stored or shared?',
    a: 'No personal data is stored by FairGate. The FairScale API analyzes publicly available on-chain data only. Your wallet address is used to fetch your score but is never persisted by our servers.'
  },
  {
    q: 'How do I increase my tier?',
    a: 'Your score reflects your on-chain activity. To improve: participate in DeFi protocols, stake SOL or LSTs, hold assets long-term (Diamond Hands), and engage with early-stage projects. Scores update in real-time when you refresh your dashboard.'
  },
  {
    q: 'Is this open source?',
    a: 'Yes. The full source code is available at github.com/fffwaves/superteam-fairgate. Built for the Superteam Earn FairScale bounty — contributions and forks are welcome.'
  }
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={styles.faqItem}>
      <button className={styles.faqQ} onClick={() => setOpen(o => !o)}>
        <span>{q}</span>
        <ChevronDown
          size={16}
          className={`${styles.faqChevron} ${open ? styles.faqChevronOpen : ''}`}
        />
      </button>
      {open && <p className={styles.faqA}>{a}</p>}
    </div>
  );
}

const TIER_DATA = [
  { name: 'Bronze', range: '0–40', color: '#cd7f32' },
  { name: 'Silver', range: '40–60', color: '#c0c0c0' },
  { name: 'Gold', range: '60–80', color: '#ffd700' },
  { name: 'Platinum', range: '80–100', color: '#e5e4e2' },
];

export default function LandingPage() {
  const { connected } = useWallet();
  const router = useRouter();

  useEffect(() => {
    if (connected) {
      router.push('/dashboard');
    }
  }, [connected, router]);

  return (
    <div className={styles.page}>
      <Navbar />

      <main className={styles.main}>
        {/* Hero */}
        <section className={styles.hero}>
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <div className={styles.badge}>
              Powered by FairScale
            </div>
            <h1 className={styles.h1}>
              The Reputation Layer /<br />
              <em className={styles.h1Accent}>of Solana.</em>
            </h1>
            <p className={styles.lead}>
              FairGate instantly verifies your on-chain history to calculate your
              FairScore. Join the elite and unlock exclusive gated benefits.
            </p>
            <div className={styles.ctaRow}>
              <WalletMultiButtonDynamic />
              <Link href="/demo" className={styles.ctaSecondary}>
                Try Demo ↗
              </Link>
              <a href="#tiers" className={styles.ctaTertiary}>
                View Tiers ↓
              </a>
            </div>
          </motion.div>
        </section>

        {/* Features */}
        <section className={styles.featuresSection}>
          <div className={styles.sectionLabel}>Why FairGate</div>
          <div className={styles.features}>
            {[
              { icon: Shield, title: 'Secure', desc: "No passwords. Only your wallet's history matters." },
              { icon: Award, title: 'Reputation', desc: 'Your score is calculated based on real on-chain activity.' },
              { icon: Lock, title: 'Gated', desc: 'Exclusive content unlocked by your performance.' },
              { icon: Zap, title: 'Instant', desc: 'Get your FairScore and tier in seconds.' },
            ].map((feature, i) => (
              <motion.div
                key={i}
                className={styles.featureItem}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.08 }}
              >
                <feature.icon size={22} className={styles.featureIcon} />
                <h3 className={styles.featureTitle}>{feature.title}</h3>
                <p className={styles.featureDesc}>{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* How It Works */}
        <section className={styles.stepsSection}>
          <div className={styles.sectionLabel}>How It Works</div>
          <div className={styles.steps}>
            {[
              {
                icon: Wallet,
                step: '01',
                title: 'Connect Wallet',
                desc: 'Link your Solana wallet — Phantom, Solflare, Coinbase Wallet, or any Wallet Standard compatible wallet.'
              },
              {
                icon: BarChart2,
                step: '02',
                title: 'Score Calculated',
                desc: 'FairScale analyzes your on-chain activity — transactions, DeFi, staking, NFTs — and computes your FairScore in real-time.'
              },
              {
                icon: Unlock,
                step: '03',
                title: 'Unlock Benefits',
                desc: 'Your tier (Bronze → Platinum) determines which gated content, signals, and communities you can access.'
              },
            ].map((item, i) => (
              <motion.div
                key={i}
                className={styles.step}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <span className={styles.stepNum}>{item.step}</span>
                <item.icon size={22} className={styles.stepIcon} />
                <h3 className={styles.stepTitle}>{item.title}</h3>
                <p className={styles.stepDesc}>{item.desc}</p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Tiers */}
        <section id="tiers" className={styles.tiersSection}>
          <div className={styles.sectionLabel}>Reputation Tiers</div>
          <div className={styles.tiersList}>
            {TIER_DATA.map((tier, i) => (
              <motion.div
                key={i}
                className={styles.tierRow}
                initial={{ opacity: 0, x: -8 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.07 }}
              >
                <div className={styles.tierLeft}>
                  <div className={styles.tierDot} style={{ background: tier.color }} />
                  <span className={styles.tierName}>{tier.name}</span>
                </div>
                <span className={styles.tierRange}>FairScore {tier.range}</span>
              </motion.div>
            ))}
          </div>
        </section>
      </main>

      {/* FAQ */}
      <section className={styles.faqSection}>
        <div className={styles.sectionLabel} style={{ marginBottom: '2rem' }}>Frequently Asked Questions</div>
        {FAQ_ITEMS.map((item, i) => (
          <FAQItem key={i} q={item.q} a={item.a} />
        ))}
      </section>

      {/* Final CTA */}
      <section className={styles.finalCta}>
        <div className={styles.finalCtaInner}>
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className={styles.finalH2}>Ready to prove your reputation?</h2>
            <p className={styles.finalDesc}>Connect your wallet and get your FairScore in seconds.</p>
            <WalletMultiButtonDynamic />
          </motion.div>
        </div>
      </section>

      <footer className={styles.footer}>
        <span>© 2026 FairGate</span>
        <span className={styles.footerDot}>·</span>
        <a href="https://fairscale.xyz" target="_blank" rel="noopener noreferrer">Powered by FairScale</a>
        <span className={styles.footerDot}>·</span>
        <a href="https://github.com/fffwaves/superteam-fairgate" target="_blank" rel="noopener noreferrer">GitHub</a>
        <span className={styles.footerDot}>·</span>
        <a href="https://solana.com" target="_blank" rel="noopener noreferrer">Built on Solana</a>
      </footer>
    </div>
  );
}
